# 核心任务
- name: MySQL
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common, tags: "role_common"} 
    - { role: role_cloud, tags: "role_cloud" } 
    - { role: role_nginx, tags: "role_nginx"}     
    - { role: grafana, tags: "grafana"}
    - { role: role_preend, tags: "role_preend" }
    - { role: role_end, tags: "role_end"}
                                     